INSERT INTO go.tbTopic (community_id, created_date, created_by, topic_name) VALUES (1, sysdate(), 1, 'Elves in the Rainbow');
INSERT INTO go.tbTopic (community_id, created_date, created_by, topic_name) VALUES (1, sysdate(), 2, 'The Snow of the Time');
INSERT INTO go.tbTopic (community_id, created_date, created_by, topic_name) VALUES (2, sysdate(), 3, 'The Sparks Gate');
INSERT INTO go.tbTopic (community_id, created_date, created_by, topic_name) VALUES (2, sysdate(), 4, 'Sorcerer of Vision');
INSERT INTO go.tbTopic (community_id, created_date, created_by, topic_name) VALUES (3, sysdate(), 5, 'The White Husband');
INSERT INTO go.tbTopic (community_id, created_date, created_by, topic_name) VALUES (3, sysdate(), 5, 'Weeping Gate');
INSERT INTO go.tbTopic (community_id, created_date, created_by, topic_name) VALUES (4, sysdate(), 4, 'Seventh Shores');
INSERT INTO go.tbTopic (community_id, created_date, created_by, topic_name) VALUES (4, sysdate(), 3, 'The Lost Search');
INSERT INTO go.tbTopic (community_id, created_date, created_by, topic_name) VALUES (5, sysdate(), 2, 'Wife of Legacy');
INSERT INTO go.tbTopic (community_id, created_date, created_by, topic_name) VALUES (5, sysdate(), 1, 'The Girls Flame');
INSERT INTO go.tbTopic (community_id, created_date, created_by, topic_name) VALUES (6, sysdate(), 1, 'The Husband of the Luck');
INSERT INTO go.tbTopic (community_id, created_date, created_by, topic_name) VALUES (6, sysdate(), 2, 'Boy in the Danger');
INSERT INTO go.tbTopic (community_id, created_date, created_by, topic_name) VALUES (7, sysdate(), 3, 'Sacred Mists');
INSERT INTO go.tbTopic (community_id, created_date, created_by, topic_name) VALUES (7, sysdate(), 3, 'The Missing Twilight');
INSERT INTO go.tbTopic (community_id, created_date, created_by, topic_name) VALUES (8, sysdate(), 4, 'Women of Sword');
INSERT INTO go.tbTopic (community_id, created_date, created_by, topic_name) VALUES (8, sysdate(), 5, 'The Courage of the Blade');
INSERT INTO go.tbTopic (community_id, created_date, created_by, topic_name) VALUES (9, sysdate(), 1, 'Future in the Future');
INSERT INTO go.tbTopic (community_id, created_date, created_by, topic_name) VALUES (9, sysdate(), 2, 'Eager Healer');
INSERT INTO go.tbTopic (community_id, created_date, created_by, topic_name) VALUES (9, sysdate(), 3, 'The Prized Rose');
INSERT INTO go.tbTopic (community_id, created_date, created_by, topic_name) VALUES (9, sysdate(), 2, 'Princess of Rings');
